# Generated by Django 5.2 on 2025-05-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_customer_email_order_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
